//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCD_Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ZH_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ZH_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCD_Framework.Resources.ZH_CN", typeof(ZH_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        internal static string btn_Apply {
            get {
                return ResourceManager.GetString("btn_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算 的本地化字符串。
        /// </summary>
        internal static string btn_Calculation {
            get {
                return ResourceManager.GetString("btn_Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string btn_Cancel {
            get {
                return ResourceManager.GetString("btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string btn_Close {
            get {
                return ResourceManager.GetString("btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string btn_Copy {
            get {
                return ResourceManager.GetString("btn_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string btn_Delete {
            get {
                return ResourceManager.GetString("btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string btn_Edit {
            get {
                return ResourceManager.GetString("btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string btn_Login {
            get {
                return ResourceManager.GetString("btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string btn_OK {
            get {
                return ResourceManager.GetString("btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string btn_Reset {
            get {
                return ResourceManager.GetString("btn_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存所有 的本地化字符串。
        /// </summary>
        internal static string btn_SaveAll {
            get {
                return ResourceManager.GetString("btn_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        internal static string btn_Use {
            get {
                return ResourceManager.GetString("btn_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机 的本地化字符串。
        /// </summary>
        internal static string common_Camera {
            get {
                return ResourceManager.GetString("common_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        internal static string common_Info {
            get {
                return ResourceManager.GetString("common_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有保存成功 的本地化字符串。
        /// </summary>
        internal static string common_SaveAllSuccess {
            get {
                return ResourceManager.GetString("common_SaveAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        internal static string common_SaveFailed {
            get {
                return ResourceManager.GetString("common_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        internal static string common_SaveSuccess {
            get {
                return ResourceManager.GetString("common_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机设置 的本地化字符串。
        /// </summary>
        internal static string faq_Text {
            get {
                return ResourceManager.GetString("faq_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算法文件 的本地化字符串。
        /// </summary>
        internal static string fctb_AF {
            get {
                return ResourceManager.GetString("fctb_AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算法文件加载失败 的本地化字符串。
        /// </summary>
        internal static string fctb_Msg1 {
            get {
                return ResourceManager.GetString("fctb_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算法文件已修改,是否保存修改过的算法文件？ 的本地化字符串。
        /// </summary>
        internal static string fctb_Msg2 {
            get {
                return ResourceManager.GetString("fctb_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑当前组件配方 的本地化字符串。
        /// </summary>
        internal static string fctb_Text {
            get {
                return ResourceManager.GetString("fctb_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空 的本地化字符串。
        /// </summary>
        internal static string fl_Msg1 {
            get {
                return ResourceManager.GetString("fl_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        internal static string fl_Msg2 {
            get {
                return ResourceManager.GetString("fl_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码不正确 的本地化字符串。
        /// </summary>
        internal static string fl_Msg3 {
            get {
                return ResourceManager.GetString("fl_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string fl_PassWard {
            get {
                return ResourceManager.GetString("fl_PassWard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string fl_UserName {
            get {
                return ResourceManager.GetString("fl_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string fm_About {
            get {
                return ResourceManager.GetString("fm_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角度补偿 的本地化字符串。
        /// </summary>
        internal static string fm_AC {
            get {
                return ResourceManager.GetString("fm_AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实际坐标信息 的本地化字符串。
        /// </summary>
        internal static string fm_ACI {
            get {
                return ResourceManager.GetString("fm_ACI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角度允许误差 的本地化字符串。
        /// </summary>
        internal static string fm_AL {
            get {
                return ResourceManager.GetString("fm_AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算法查看 的本地化字符串。
        /// </summary>
        internal static string fm_Algorithm {
            get {
                return ResourceManager.GetString("fm_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机 的本地化字符串。
        /// </summary>
        internal static string fm_Camera {
            get {
                return ResourceManager.GetString("fm_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯数据 的本地化字符串。
        /// </summary>
        internal static string fm_CD {
            get {
                return ResourceManager.GetString("fm_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接详情 的本地化字符串。
        /// </summary>
        internal static string fm_ConnDetails {
            get {
                return ResourceManager.GetString("fm_ConnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机拍照模式 的本地化字符串。
        /// </summary>
        internal static string fm_CPM {
            get {
                return ResourceManager.GetString("fm_CPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机参数设置 的本地化字符串。
        /// </summary>
        internal static string fm_CPS {
            get {
                return ResourceManager.GetString("fm_CPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前组件标准信息 的本地化字符串。
        /// </summary>
        internal static string fm_CPSI {
            get {
                return ResourceManager.GetString("fm_CPSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string fm_Help {
            get {
                return ResourceManager.GetString("fm_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像保存 的本地化字符串。
        /// </summary>
        internal static string fm_ImageSave {
            get {
                return ResourceManager.GetString("fm_ImageSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量长度超出了标准值，请检查中间边缘部分是否找错 的本地化字符串。
        /// </summary>
        internal static string fm_LNG {
            get {
                return ResourceManager.GetString("fm_LNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左侧运行状态 的本地化字符串。
        /// </summary>
        internal static string fm_LRS {
            get {
                return ResourceManager.GetString("fm_LRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增组件配方 的本地化字符串。
        /// </summary>
        internal static string fm_menu_File1 {
            get {
                return ResourceManager.GetString("fm_menu_File1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换组件配方 的本地化字符串。
        /// </summary>
        internal static string fm_menu_File2 {
            get {
                return ResourceManager.GetString("fm_menu_File2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑当前组件配方 的本地化字符串。
        /// </summary>
        internal static string fm_menu_File3 {
            get {
                return ResourceManager.GetString("fm_menu_File3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑基础组件配方 的本地化字符串。
        /// </summary>
        internal static string fm_menu_File4 {
            get {
                return ResourceManager.GetString("fm_menu_File4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string fm_menu_Files {
            get {
                return ResourceManager.GetString("fm_menu_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限登录 的本地化字符串。
        /// </summary>
        internal static string fm_menu_PL {
            get {
                return ResourceManager.GetString("fm_menu_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中点坐标1 的本地化字符串。
        /// </summary>
        internal static string fm_Mid1 {
            get {
                return ResourceManager.GetString("fm_Mid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中点坐标2 的本地化字符串。
        /// </summary>
        internal static string fm_Mid2 {
            get {
                return ResourceManager.GetString("fm_Mid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件参数格式出错! 的本地化字符串。
        /// </summary>
        internal static string fm_Msg1 {
            get {
                return ResourceManager.GetString("fm_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载模式界面 的本地化字符串。
        /// </summary>
        internal static string fm_Msg10 {
            get {
                return ResourceManager.GetString("fm_Msg10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件参数格式出错! 的本地化字符串。
        /// </summary>
        internal static string fm_Msg11 {
            get {
                return ResourceManager.GetString("fm_Msg11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接TCP 的本地化字符串。
        /// </summary>
        internal static string fm_Msg111 {
            get {
                return ResourceManager.GetString("fm_Msg111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载产品标准数据 的本地化字符串。
        /// </summary>
        internal static string fm_Msg12 {
            get {
                return ResourceManager.GetString("fm_Msg12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载完成 的本地化字符串。
        /// </summary>
        internal static string fm_Msg13 {
            get {
                return ResourceManager.GetString("fm_Msg13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机配置文件不存在 的本地化字符串。
        /// </summary>
        internal static string fm_Msg14 {
            get {
                return ResourceManager.GetString("fm_Msg14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机配置文件不存在 的本地化字符串。
        /// </summary>
        internal static string fm_Msg141 {
            get {
                return ResourceManager.GetString("fm_Msg141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算法文件不存在 的本地化字符串。
        /// </summary>
        internal static string fm_Msg15 {
            get {
                return ResourceManager.GetString("fm_Msg15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机连接成功 的本地化字符串。
        /// </summary>
        internal static string fm_Msg16 {
            get {
                return ResourceManager.GetString("fm_Msg16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败 的本地化字符串。
        /// </summary>
        internal static string fm_Msg17 {
            get {
                return ResourceManager.GetString("fm_Msg17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍摄未找到电池片\r\n请确认电池片在视野范围内并且未变形或损坏或被其它障碍物遮挡 的本地化字符串。
        /// </summary>
        internal static string fm_Msg18 {
            get {
                return ResourceManager.GetString("fm_Msg18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍摄未找到电池片引脚\r\n请确认电池片引脚未变形或损坏或被其它障碍物遮挡 的本地化字符串。
        /// </summary>
        internal static string fm_Msg19 {
            get {
                return ResourceManager.GetString("fm_Msg19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照数量配置参数必须大于0并且小于10 的本地化字符串。
        /// </summary>
        internal static string fm_Msg2 {
            get {
                return ResourceManager.GetString("fm_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电池片X方向超出相机视野允许范围 的本地化字符串。
        /// </summary>
        internal static string fm_Msg20 {
            get {
                return ResourceManager.GetString("fm_Msg20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照数量配置参数必须大于0并且小于10 的本地化字符串。
        /// </summary>
        internal static string fm_Msg21 {
            get {
                return ResourceManager.GetString("fm_Msg21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电池片Y方向超出相机视野允许范围 的本地化字符串。
        /// </summary>
        internal static string fm_Msg211 {
            get {
                return ResourceManager.GetString("fm_Msg211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电池片角度Angle方向超出视野允许范围 的本地化字符串。
        /// </summary>
        internal static string fm_Msg22 {
            get {
                return ResourceManager.GetString("fm_Msg22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接成功 的本地化字符串。
        /// </summary>
        internal static string fm_Msg23 {
            get {
                return ResourceManager.GetString("fm_Msg23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开连接 的本地化字符串。
        /// </summary>
        internal static string fm_Msg24 {
            get {
                return ResourceManager.GetString("fm_Msg24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已登录 的本地化字符串。
        /// </summary>
        internal static string fm_Msg25 {
            get {
                return ResourceManager.GetString("fm_Msg25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机和算法文件在配置文件中的值必须要大于0 的本地化字符串。
        /// </summary>
        internal static string fm_Msg3 {
            get {
                return ResourceManager.GetString("fm_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查相机配置文件路径 的本地化字符串。
        /// </summary>
        internal static string fm_Msg4 {
            get {
                return ResourceManager.GetString("fm_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载相机配置文件 的本地化字符串。
        /// </summary>
        internal static string fm_Msg5 {
            get {
                return ResourceManager.GetString("fm_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查算法配置文件路径 的本地化字符串。
        /// </summary>
        internal static string fm_Msg6 {
            get {
                return ResourceManager.GetString("fm_Msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载算法文件 的本地化字符串。
        /// </summary>
        internal static string fm_Msg7 {
            get {
                return ResourceManager.GetString("fm_Msg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接相机 的本地化字符串。
        /// </summary>
        internal static string fm_Msg8 {
            get {
                return ResourceManager.GetString("fm_Msg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载菜单下拉选项 的本地化字符串。
        /// </summary>
        internal static string fm_Msg9 {
            get {
                return ResourceManager.GetString("fm_Msg9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重载算法进度 的本地化字符串。
        /// </summary>
        internal static string fm_OAS {
            get {
                return ResourceManager.GetString("fm_OAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运算结果 的本地化字符串。
        /// </summary>
        internal static string fm_OR {
            get {
                return ResourceManager.GetString("fm_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行结果1 的本地化字符串。
        /// </summary>
        internal static string fm_OR1 {
            get {
                return ResourceManager.GetString("fm_OR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行结果2 的本地化字符串。
        /// </summary>
        internal static string fm_OR2 {
            get {
                return ResourceManager.GetString("fm_OR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行次数 的本地化字符串。
        /// </summary>
        internal static string fm_OT {
            get {
                return ResourceManager.GetString("fm_OT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A点坐标 的本地化字符串。
        /// </summary>
        internal static string fm_PA {
            get {
                return ResourceManager.GetString("fm_PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B点坐标 的本地化字符串。
        /// </summary>
        internal static string fm_PB {
            get {
                return ResourceManager.GetString("fm_PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组件补偿 的本地化字符串。
        /// </summary>
        internal static string fm_PC {
            get {
                return ResourceManager.GetString("fm_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中点坐标 的本地化字符串。
        /// </summary>
        internal static string fm_PM {
            get {
                return ResourceManager.GetString("fm_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组件名称 的本地化字符串。
        /// </summary>
        internal static string fm_PN {
            get {
                return ResourceManager.GetString("fm_PN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器人补偿 的本地化字符串。
        /// </summary>
        internal static string fm_RC {
            get {
                return ResourceManager.GetString("fm_RC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收 的本地化字符串。
        /// </summary>
        internal static string fm_Rec {
            get {
                return ResourceManager.GetString("fm_Rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右侧运行状态 的本地化字符串。
        /// </summary>
        internal static string fm_RRS {
            get {
                return ResourceManager.GetString("fm_RRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行状态 的本地化字符串。
        /// </summary>
        internal static string fm_RS {
            get {
                return ResourceManager.GetString("fm_RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基准数据配置 的本地化字符串。
        /// </summary>
        internal static string fm_SDC {
            get {
                return ResourceManager.GetString("fm_SDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        internal static string fm_Send {
            get {
                return ResourceManager.GetString("fm_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        internal static string fm_SS {
            get {
                return ResourceManager.GetString("fm_SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否发送数据（电池片宽度或长度异常） 的本地化字符串。
        /// </summary>
        internal static string fm_SWL {
            get {
                return ResourceManager.GetString("fm_SWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TCP通讯 的本地化字符串。
        /// </summary>
        internal static string fm_TCP_Comm {
            get {
                return ResourceManager.GetString("fm_TCP_Comm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TCP连接 的本地化字符串。
        /// </summary>
        internal static string fm_TCP_Conn {
            get {
                return ResourceManager.GetString("fm_TCP_Conn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传图片模式 的本地化字符串。
        /// </summary>
        internal static string fm_UPM {
            get {
                return ResourceManager.GetString("fm_UPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量宽度超出了标准值，请检查两边边缘部分是否找错 的本地化字符串。
        /// </summary>
        internal static string fm_WNG {
            get {
                return ResourceManager.GetString("fm_WNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X允许误差 的本地化字符串。
        /// </summary>
        internal static string fm_XDL {
            get {
                return ResourceManager.GetString("fm_XDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X,Y方向补偿 的本地化字符串。
        /// </summary>
        internal static string fm_XYC {
            get {
                return ResourceManager.GetString("fm_XYC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y允许误差 的本地化字符串。
        /// </summary>
        internal static string fm_YDL {
            get {
                return ResourceManager.GetString("fm_YDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算法查看 的本地化字符串。
        /// </summary>
        internal static string fqb_Text {
            get {
                return ResourceManager.GetString("fqb_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 摆串机纠偏 的本地化字符串。
        /// </summary>
        internal static string frmMain_Text {
            get {
                return ResourceManager.GetString("frmMain_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英语 的本地化字符串。
        /// </summary>
        internal static string fs_EN {
            get {
                return ResourceManager.GetString("fs_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行模式选择 的本地化字符串。
        /// </summary>
        internal static string fs_Gb1 {
            get {
                return ResourceManager.GetString("fs_Gb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言选择 的本地化字符串。
        /// </summary>
        internal static string fs_Gb2 {
            get {
                return ResourceManager.GetString("fs_Gb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机拍照 的本地化字符串。
        /// </summary>
        internal static string fs_Photograph {
            get {
                return ResourceManager.GetString("fs_Photograph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设定 的本地化字符串。
        /// </summary>
        internal static string fs_Text {
            get {
                return ResourceManager.GetString("fs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片上传 的本地化字符串。
        /// </summary>
        internal static string fs_Upload {
            get {
                return ResourceManager.GetString("fs_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        internal static string fs_ZH {
            get {
                return ResourceManager.GetString("fs_ZH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角度允许偏差 的本地化字符串。
        /// </summary>
        internal static string fsd_AL {
            get {
                return ResourceManager.GetString("fsd_AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角度1 的本地化字符串。
        /// </summary>
        internal static string fsd_Angle1 {
            get {
                return ResourceManager.GetString("fsd_Angle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角度2 的本地化字符串。
        /// </summary>
        internal static string fsd_Angle2 {
            get {
                return ResourceManager.GetString("fsd_Angle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串长 的本地化字符串。
        /// </summary>
        internal static string fsd_CL {
            get {
                return ResourceManager.GetString("fsd_CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常量 的本地化字符串。
        /// </summary>
        internal static string fsd_Constant {
            get {
                return ResourceManager.GetString("fsd_Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中心旋转角度 的本地化字符串。
        /// </summary>
        internal static string fsd_CRA {
            get {
                return ResourceManager.GetString("fsd_CRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 偏差 的本地化字符串。
        /// </summary>
        internal static string fsd_Lt {
            get {
                return ResourceManager.GetString("fsd_Lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中点坐标1 的本地化字符串。
        /// </summary>
        internal static string fsd_Mid1 {
            get {
                return ResourceManager.GetString("fsd_Mid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中点坐标2 的本地化字符串。
        /// </summary>
        internal static string fsd_Mid2 {
            get {
                return ResourceManager.GetString("fsd_Mid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前运行的配方不能删除 的本地化字符串。
        /// </summary>
        internal static string fsd_Msg1 {
            get {
                return ResourceManager.GetString("fsd_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要删除该配方数据吗 的本地化字符串。
        /// </summary>
        internal static string fsd_Msg2 {
            get {
                return ResourceManager.GetString("fsd_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对应的算法文件也会一起删除 的本地化字符串。
        /// </summary>
        internal static string fsd_Msg3 {
            get {
                return ResourceManager.GetString("fsd_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要复制该配方数据吗 的本地化字符串。
        /// </summary>
        internal static string fsd_Msg4 {
            get {
                return ResourceManager.GetString("fsd_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先点击编辑按钮再重新编辑保存 的本地化字符串。
        /// </summary>
        internal static string fsd_Msg5 {
            get {
                return ResourceManager.GetString("fsd_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入格式错误 的本地化字符串。
        /// </summary>
        internal static string fsd_Msg6 {
            get {
                return ResourceManager.GetString("fsd_Msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string fsd_Note {
            get {
                return ResourceManager.GetString("fsd_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组件名称 的本地化字符串。
        /// </summary>
        internal static string fsd_PN {
            get {
                return ResourceManager.GetString("fsd_PN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基准数据配置 的本地化字符串。
        /// </summary>
        internal static string fsd_Text {
            get {
                return ResourceManager.GetString("fsd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组件X方向移动偏差 的本地化字符串。
        /// </summary>
        internal static string fsd_XDC {
            get {
                return ResourceManager.GetString("fsd_XDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X允许误差 的本地化字符串。
        /// </summary>
        internal static string fsd_XDL {
            get {
                return ResourceManager.GetString("fsd_XDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组件Y方向移动偏差 的本地化字符串。
        /// </summary>
        internal static string fsd_YDC {
            get {
                return ResourceManager.GetString("fsd_YDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y允许误差 的本地化字符串。
        /// </summary>
        internal static string fsd_YDL {
            get {
                return ResourceManager.GetString("fsd_YDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用组件 的本地化字符串。
        /// </summary>
        internal static string fstb_EP {
            get {
                return ResourceManager.GetString("fstb_EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否确定启用该组件配方? 的本地化字符串。
        /// </summary>
        internal static string fstb_Msg1 {
            get {
                return ResourceManager.GetString("fstb_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换组件配方 的本地化字符串。
        /// </summary>
        internal static string fstb_Text {
            get {
                return ResourceManager.GetString("fstb_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组件名称不能为空 的本地化字符串。
        /// </summary>
        internal static string ftba_Msg1 {
            get {
                return ResourceManager.GetString("ftba_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算法文件不存在 的本地化字符串。
        /// </summary>
        internal static string ftba_Msg2_f {
            get {
                return ResourceManager.GetString("ftba_Msg2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础组件配方 的本地化字符串。
        /// </summary>
        internal static string ftba_Msg2_h {
            get {
                return ResourceManager.GetString("ftba_Msg2_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用该组件配方 的本地化字符串。
        /// </summary>
        internal static string ftba_Msg3 {
            get {
                return ResourceManager.GetString("ftba_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组件名称 的本地化字符串。
        /// </summary>
        internal static string ftba_PN {
            get {
                return ResourceManager.GetString("ftba_PN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增组件配方 的本地化字符串。
        /// </summary>
        internal static string ftba_Text {
            get {
                return ResourceManager.GetString("ftba_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动生成日期文件夹 的本地化字符串。
        /// </summary>
        internal static string is_AF {
            get {
                return ResourceManager.GetString("is_AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有图片 的本地化字符串。
        /// </summary>
        internal static string is_AP {
            get {
                return ResourceManager.GetString("is_AP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览... 的本地化字符串。
        /// </summary>
        internal static string is_Browse {
            get {
                return ResourceManager.GetString("is_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正确图片 的本地化字符串。
        /// </summary>
        internal static string is_CP {
            get {
                return ResourceManager.GetString("is_CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像保存格式 的本地化字符串。
        /// </summary>
        internal static string is_IPF {
            get {
                return ResourceManager.GetString("is_IPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像保存路径 的本地化字符串。
        /// </summary>
        internal static string is_IPP {
            get {
                return ResourceManager.GetString("is_IPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择文件夹 的本地化字符串。
        /// </summary>
        internal static string is_Msg1 {
            get {
                return ResourceManager.GetString("is_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要保存的图片 的本地化字符串。
        /// </summary>
        internal static string is_PS {
            get {
                return ResourceManager.GetString("is_PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片名称以日期时间命名 的本地化字符串。
        /// </summary>
        internal static string is_PT {
            get {
                return ResourceManager.GetString("is_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否保存图片到本地 的本地化字符串。
        /// </summary>
        internal static string is_SPL {
            get {
                return ResourceManager.GetString("is_SPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用Cognex工具保存图片 的本地化字符串。
        /// </summary>
        internal static string is_ST {
            get {
                return ResourceManager.GetString("is_ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像保存设置 的本地化字符串。
        /// </summary>
        internal static string is_Text {
            get {
                return ResourceManager.GetString("is_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误图片 的本地化字符串。
        /// </summary>
        internal static string is_WP {
            get {
                return ResourceManager.GetString("is_WP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动 的本地化字符串。
        /// </summary>
        internal static string pm_Auto {
            get {
                return ResourceManager.GetString("pm_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动 的本地化字符串。
        /// </summary>
        internal static string pm_Manual {
            get {
                return ResourceManager.GetString("pm_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在实时显示...... 的本地化字符串。
        /// </summary>
        internal static string pm_Msg1 {
            get {
                return ResourceManager.GetString("pm_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照 的本地化字符串。
        /// </summary>
        internal static string pm_Photograph {
            get {
                return ResourceManager.GetString("pm_Photograph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实时显示 的本地化字符串。
        /// </summary>
        internal static string pm_RTD {
            get {
                return ResourceManager.GetString("pm_RTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止实时 的本地化字符串。
        /// </summary>
        internal static string pm_SR {
            get {
                return ResourceManager.GetString("pm_SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有文件 的本地化字符串。
        /// </summary>
        internal static string um_AF {
            get {
                return ResourceManager.GetString("um_AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择图片 的本地化字符串。
        /// </summary>
        internal static string um_CI {
            get {
                return ResourceManager.GetString("um_CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        internal static string um_Run {
            get {
                return ResourceManager.GetString("um_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传图片 的本地化字符串。
        /// </summary>
        internal static string um_UP {
            get {
                return ResourceManager.GetString("um_UP", resourceCulture);
            }
        }
    }
}
